name: "\U0001F41B Bug report"
description: Report a bug or unexpected behavior in the solution accelerator
title: "[Bug]: "
labels: [bug]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the solution is affected?
      options:
        - Infrastructure (Bicep/infra)
        - Application Services (API, Functions, etc.)
        - UI (Web app, Portal, etc.)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: OS, Azure CLI version, Bicep version, etc.
      placeholder: "e.g., Windows 11, Azure CLI 2.56.0, Bicep 0.22.6"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the problem here.
    validations:
      required: false
