name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml
    permissions:
      contents: read

  lint-build-and-test-dotnet-apps:
    name: Lint, Build, Test and Publish .NET Apps
    uses: ./.github/workflows/lint-build-test-and-publish-dotnet-apps.yml
    permissions:
      contents: read